apiVersion: v1
kind: ServiceAccount
metadata:
  name: headlamp
  namespace: headlamp
  labels:
    app.kubernetes.io/name: headlamp
    app.kubernetes.io/component: server
    app.kubernetes.io/part-of: platform-gitops
automountServiceAccountToken: false
