apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - serviceaccounts.yaml
  - runtime-secrets-rbac.yaml
  - trust-bundles.yaml
  - vault-agent-config.yaml
  - secret-bootstrap-script.yaml
  - secret-bootstrap-job.yaml
  - operator
  - project-playbook.yaml
  - awx.yaml
  - verifier-config.yaml
  - verifier.yaml
  - provision-script.yaml
  - provision-job.yaml
