apiVersion: v1
kind: ServiceAccount
metadata:
  name: awx-vault-bootstrap
  namespace: awx
  annotations: {argocd.argoproj.io/sync-wave: "-9"}
automountServiceAccountToken: false
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: awx-provisioner
  namespace: awx
  annotations: {argocd.argoproj.io/sync-wave: "-9"}
automountServiceAccountToken: false
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: awx-verifier
  namespace: awx
  annotations: {argocd.argoproj.io/sync-wave: "-9"}
automountServiceAccountToken: false
