apiVersion: velero.io/v1
kind: Restore
metadata:
  name: bkp-02-restore-20260801
  namespace: velero
  labels:
    app.kubernetes.io/part-of: bkp-02-validation
spec:
  backupName: bkp-02-validation-20260801
