apiVersion: v1
kind: ServiceAccount
metadata:
  name: renovate
  namespace: renovate
  annotations:
    argocd.argoproj.io/sync-wave: "-2"
  labels:
    app.kubernetes.io/name: renovate
    app.kubernetes.io/part-of: platform-gitops
automountServiceAccountToken: false
