apiVersion: v1
kind: Namespace
metadata:
  name: board-demo
  annotations:
    argocd.argoproj.io/sync-wave: "-3"
  labels:
    app.kubernetes.io/name: board-demo
    app.kubernetes.io/part-of: platform-gitops
    pod-security.kubernetes.io/enforce: restricted
    pod-security.kubernetes.io/enforce-version: latest
