apiVersion: v1
kind: ServiceAccount
metadata:
  name: board-demo
  namespace: board-demo
  annotations:
    argocd.argoproj.io/sync-wave: "-2"
  labels:
    app.kubernetes.io/name: board-demo
    app.kubernetes.io/component: application
    app.kubernetes.io/part-of: platform-gitops
automountServiceAccountToken: false
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: board-demo-vault-bootstrap
  namespace: board-demo
  annotations:
    argocd.argoproj.io/sync-wave: "-2"
  labels:
    app.kubernetes.io/name: board-demo
    app.kubernetes.io/component: runtime-bootstrap
    app.kubernetes.io/part-of: platform-gitops
automountServiceAccountToken: false
