apiVersion: v1
kind: Service
metadata:
  name: sonarqube
  namespace: sonarqube
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
  labels:
    app.kubernetes.io/name: sonarqube
    app.kubernetes.io/component: server
    app.kubernetes.io/part-of: platform-gitops
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: sonarqube
    app.kubernetes.io/component: server
  ports:
    - name: http
      port: 9000
      targetPort: http
      protocol: TCP
