apiVersion: v1
kind: ServiceAccount
metadata:
  name: sonarqube
  namespace: sonarqube
  annotations:
    argocd.argoproj.io/sync-wave: "-2"
  labels:
    app.kubernetes.io/name: sonarqube
    app.kubernetes.io/component: server
    app.kubernetes.io/part-of: platform-gitops
automountServiceAccountToken: false
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: sonarqube-verifier
  namespace: sonarqube
  annotations:
    argocd.argoproj.io/sync-wave: "-2"
  labels:
    app.kubernetes.io/name: sonarqube
    app.kubernetes.io/component: verification
    app.kubernetes.io/part-of: platform-gitops
automountServiceAccountToken: false
