apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - serviceaccounts.yaml
  - indexer.yaml
  - bootstrap-job.yaml
  - oidc-security-sync-job.yaml
  - manager.yaml
  - dashboard.yaml
  - network-policies.yaml
  - wazuh-04-relay-agent.yaml
configMapGenerator:
  - name: wazuh-vault-agent
    namespace: wazuh
    files:
      - vault-agent-indexer.hcl=files/vault-agent-indexer.hcl
      - vault-agent-manager.hcl=files/vault-agent-manager.hcl
      - vault-agent-bootstrap.hcl=files/vault-agent-bootstrap.hcl
      - vault-agent-dashboard.hcl=files/vault-agent-dashboard.hcl
      - vault-agent-relay-agent.hcl=files/vault-agent-relay-agent.hcl
      - vault.crt=files/vault.crt
  - name: wazuh-04-relay-agent-conf
    namespace: wazuh
    files:
      - ossec.conf=files/wazuh-04-relay-agent-ossec.conf
  - name: wazuh-dashboard-conf
    namespace: wazuh
    files:
      - opensearch_dashboards.yml=files/opensearch_dashboards.yml
  - name: wazuh-indexer-conf
    namespace: wazuh
    files:
      - opensearch.yml=files/opensearch.yml
  - name: wazuh-manager-conf
    namespace: wazuh
    files:
      - ossec.conf=files/ossec.conf
  - name: wazuh-manager-rules
    namespace: wazuh
    files:
      - wazuh-01-a90-k8s-audit.xml=files/wazuh-01-a90-k8s-audit.xml
      - wazuh-01-d30-suricata.xml=files/wazuh-01-d30-suricata.xml
      - wazuh-04-a90-idp-access.xml=files/wazuh-04-a90-idp-access.xml
      - wazuh-04-d30-waf-runtime.xml=files/wazuh-04-d30-waf-runtime.xml
      - wazuh-04-decoders.xml=files/wazuh-04-decoders.xml
  - name: wazuh-manager-cont-init
    namespace: wazuh
    files:
      - 3-wazuh-01-index-routing=files/3-wazuh-01-index-routing
  - name: wazuh-manager-soar01-integration
    namespace: wazuh
    files:
      - custom-soar01=files/custom-soar01
  - name: wazuh-bootstrap-script
    namespace: wazuh
    files:
      - bootstrap-retention.py=files/bootstrap-retention.py
  - name: wazuh-oidc-security-script
    namespace: wazuh
    files:
      - sync-oidc-security.py=files/sync-oidc-security.py
generatorOptions:
  disableNameSuffixHash: true
