apiVersion: v1
kind: ServiceAccount
metadata:
  name: wazuh-indexer
  namespace: wazuh
  labels:
    app.kubernetes.io/name: wazuh
    app.kubernetes.io/component: indexer
automountServiceAccountToken: false
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: wazuh-manager
  namespace: wazuh
  labels:
    app.kubernetes.io/name: wazuh
    app.kubernetes.io/component: manager
automountServiceAccountToken: false
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: wazuh-bootstrap
  namespace: wazuh
  labels:
    app.kubernetes.io/name: wazuh
    app.kubernetes.io/component: bootstrap
automountServiceAccountToken: false
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: wazuh-dashboard
  namespace: wazuh
  labels:
    app.kubernetes.io/name: wazuh
    app.kubernetes.io/component: dashboard
automountServiceAccountToken: false
