apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - install.yaml
  - monitoring.yaml
  - alerting-rules.yaml
  - alerting-receiver.yaml
  - slack-egress-proxy.yaml
  - network-policies.yaml
  - loki-host-gateway.yaml
  - dashboard.yaml
  - dashboard-capacity.yaml
  - dashboard-core-services.yaml
  - dashboard-backup-pipelines.yaml
  - dashboard-loki-log-explorer.yaml
  - dashboard-argocd-application-overview.yaml
  - dashboard-kubernetes-global.yaml
  - dashboard-node-exporter-full.yaml
configMapGenerator:
  - name: obs-grafana-runtime-config
    namespace: obs
    files:
      - vault-agent.hcl=files/vault-agent.hcl
      - vault.crt=files/vault.crt
  - name: obs-alertmanager-runtime-config
    namespace: obs
    files:
      - vault-agent-alertmanager.hcl=files/vault-agent-alertmanager.hcl
      - vault.crt=files/vault.crt
  - name: obs-18-slack-egress-proxy
    namespace: obs
    files:
      - obs-18-slack-egress-proxy.py=files/obs-18-slack-egress-proxy.py
generatorOptions:
  disableNameSuffixHash: true
