apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - install.yaml
  - monitoring.yaml
  - network-policies.yaml
  - dashboard.yaml
  - dashboard-capacity.yaml
  - dashboard-core-services.yaml
  - dashboard-backup-pipelines.yaml
  - dashboard-loki-log-explorer.yaml
  - dashboard-argocd-application-overview.yaml
configMapGenerator:
  - name: obs-grafana-runtime-config
    namespace: obs
    files:
      - vault-agent.hcl=files/vault-agent.hcl
      - vault.crt=files/vault.crt
generatorOptions:
  disableNameSuffixHash: true
