apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: obs-traefik
  namespace: obs
  labels:
    release: obs
    app.kubernetes.io/part-of: platform-gitops
spec:
  namespaceSelector:
    matchNames: [kube-system]
  selector:
    matchLabels:
      app.kubernetes.io/name: traefik
      app.kubernetes.io/component: metrics
  jobLabel: app.kubernetes.io/name
  endpoints:
    - port: metrics
      path: /metrics
      interval: 30s
      scrapeTimeout: 10s
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: obs-velero
  namespace: obs
  labels:
    release: obs
    app.kubernetes.io/part-of: platform-gitops
spec:
  namespaceSelector:
    matchNames: [velero]
  selector:
    matchLabels:
      app.kubernetes.io/instance: velero
      app.kubernetes.io/name: velero
  endpoints:
    - port: http-monitoring
      path: /metrics
      interval: 30s
      scrapeTimeout: 10s
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: obs-loki
  namespace: obs
  labels:
    release: obs
    app.kubernetes.io/part-of: platform-gitops
spec:
  namespaceSelector:
    matchNames: [loki]
  selector:
    matchLabels:
      app.kubernetes.io/instance: loki
      app.kubernetes.io/name: loki
  endpoints:
    - port: http-metrics
      path: /metrics
      interval: 30s
      scrapeTimeout: 10s
---
apiVersion: monitoring.coreos.com/v1alpha1
kind: ScrapeConfig
metadata:
  name: opnsense-node
  namespace: obs
  labels:
    release: obs
    app.kubernetes.io/part-of: platform-gitops
spec:
  metricsPath: /metrics
  scrapeInterval: 30s
  scrapeTimeout: 10s
  staticConfigs:
    - targets:
        - 10.10.10.1:9100
      labels:
        instance: opnsense.imcherry5778.xyz
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: obs-alloy
  namespace: obs
  labels:
    release: obs
    app.kubernetes.io/part-of: platform-gitops
spec:
  namespaceSelector:
    matchNames: [loki]
  selector:
    matchLabels:
      app.kubernetes.io/instance: alloy
      app.kubernetes.io/name: alloy
  endpoints:
    - port: http-metrics
      path: /metrics
      interval: 30s
      scrapeTimeout: 10s
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: obs-argocd-application-controller
  namespace: obs
  labels:
    release: obs
    app.kubernetes.io/part-of: platform-gitops
spec:
  namespaceSelector:
    matchNames: [argocd]
  selector:
    matchLabels:
      app.kubernetes.io/component: metrics
      app.kubernetes.io/name: argocd-metrics
      app.kubernetes.io/part-of: argocd
  endpoints:
    - port: metrics
      path: /metrics
      interval: 30s
      scrapeTimeout: 10s
      metricRelabelings:
        - action: keep
          sourceLabels: [__name__]
          regex: argocd_app_info|argocd_app_sync_total
        - action: labeldrop
          regex: repo|operation|dry_run
