apiVersion: v1
kind: ServiceAccount
metadata:
  name: e2e-01-vault-bootstrap
  namespace: e2e-01
  annotations:
    argocd.argoproj.io/sync-wave: "-2"
  labels:
    app.kubernetes.io/name: e2e-01
    app.kubernetes.io/component: secret-bootstrap
    app.kubernetes.io/part-of: platform-gitops
automountServiceAccountToken: false
