apiVersion: v1
kind: Service
metadata:
  name: frontend
  namespace: hr-system
  annotations:
    argocd.argoproj.io/sync-wave: "1"
  labels:
    app.kubernetes.io/name: frontend
    app.kubernetes.io/part-of: hr-system
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: frontend
  ports:
    - name: http
      port: 80
      targetPort: http
      protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: employee-service
  namespace: hr-system
  annotations:
    argocd.argoproj.io/sync-wave: "1"
  labels:
    app.kubernetes.io/name: employee-service
    app.kubernetes.io/part-of: hr-system
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: employee-service
  ports:
    - name: http
      port: 80
      targetPort: http
      protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: hr-service
  namespace: hr-system
  annotations:
    argocd.argoproj.io/sync-wave: "1"
  labels:
    app.kubernetes.io/name: hr-service
    app.kubernetes.io/part-of: hr-system
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: hr-service
  ports:
    - name: http
      port: 80
      targetPort: http
      protocol: TCP
