apiVersion: v1
kind: ServiceAccount
metadata:
  name: frontend
  namespace: hr-system
  annotations:
    argocd.argoproj.io/sync-wave: "-2"
automountServiceAccountToken: false
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: employee-service
  namespace: hr-system
  annotations:
    argocd.argoproj.io/sync-wave: "-2"
    eks.amazonaws.com/role-arn: arn:aws:iam::465137780685:role/hr-system-prod-employee-service-role
automountServiceAccountToken: false
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: hr-service
  namespace: hr-system
  annotations:
    argocd.argoproj.io/sync-wave: "-2"
    eks.amazonaws.com/role-arn: arn:aws:iam::465137780685:role/hr-system-prod-hr-service-role
automountServiceAccountToken: false
