apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: vault-data
  namespace: vault
  labels:
    app.kubernetes.io/part-of: platform-gitops
    app.kubernetes.io/name: vault
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-path
  resources:
    requests:
      storage: 4Gi
