apiVersion: v1
kind: ServiceAccount
metadata:
  name: vault
  namespace: vault
  labels:
    app.kubernetes.io/part-of: platform-gitops
    app.kubernetes.io/name: vault
automountServiceAccountToken: false
