apiVersion: v1
kind: ServiceAccount
metadata:
  name: shuffle-opensearch
  namespace: shuffle
  labels:
    app.kubernetes.io/name: shuffle
    app.kubernetes.io/component: opensearch
automountServiceAccountToken: false
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: shuffle-backend
  namespace: shuffle
  labels:
    app.kubernetes.io/name: shuffle
    app.kubernetes.io/component: backend
automountServiceAccountToken: false
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: shuffle-frontend
  namespace: shuffle
  labels:
    app.kubernetes.io/name: shuffle
    app.kubernetes.io/component: frontend
automountServiceAccountToken: false
