apiVersion: v1
kind: ConfigMap
metadata:
  name: crowdsec-01-appsec-configs
  labels:
    app.kubernetes.io/part-of: crowdsec-01
binaryData:
{{- $root := . }}
{{- range $path, $_ := .Files.Glob "files/appsec/configs/*" }}
  {{ base $path }}: {{ $root.Files.Get $path | b64enc | quote }}
{{- end }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: crowdsec-01-appsec-rules
  labels:
    app.kubernetes.io/part-of: crowdsec-01
binaryData:
{{- range $path, $_ := .Files.Glob "files/appsec/rules/*" }}
  {{ base $path }}: {{ $root.Files.Get $path | b64enc | quote }}
{{- end }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: crowdsec-01-crs-snapshot
  labels:
    app.kubernetes.io/part-of: crowdsec-01
data:
  ARCHIVE.SHA256: |-
{{ $root.Files.Get "crs-snapshot.tar.gz.SHA256" | indent 4 }}
binaryData:
  crs-snapshot.tar.gz: {{ $root.Files.Get "files/crs-snapshot.tar.gz" | b64enc | quote }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: crowdsec-01-offline-startup-builder
  labels:
    app.kubernetes.io/part-of: crowdsec-01
binaryData:
  prepare-offline-startup.sh: {{ $root.Files.Get "files/appsec/prepare-offline-startup.sh" | b64enc | quote }}
