apiVersion: v1
kind: Service
metadata:
  name: dashy
  namespace: pomerium
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
  labels:
    app.kubernetes.io/name: dashy
    app.kubernetes.io/component: portal
    app.kubernetes.io/part-of: platform-gitops
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: dashy
    app.kubernetes.io/component: portal
  ports:
    - name: http
      port: 8080
      targetPort: http
      protocol: TCP
