apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
configMapGenerator:
  - name: pomerium-config
    namespace: pomerium
    files:
      - config.yaml=pomerium-conf.yaml
    options:
      annotations:
        argocd.argoproj.io/sync-wave: "-2"
      labels:
        app.kubernetes.io/name: pomerium
        app.kubernetes.io/component: server
        app.kubernetes.io/part-of: platform-gitops
  - name: dashy-config
    namespace: pomerium
    files:
      - conf.yml=dashy-conf.yml
    options:
      annotations:
        argocd.argoproj.io/sync-wave: "-2"
      labels:
        app.kubernetes.io/name: dashy
        app.kubernetes.io/component: portal
        app.kubernetes.io/part-of: platform-gitops
resources:
  - namespace.yaml
  - serviceaccount.yaml
  - trust-bundle.yaml
  - vault-agent-config.yaml
  - service.yaml
  - deployment.yaml
  - dashy-service.yaml
  - dashy-deployment.yaml
  - gitea-egress.yaml
  - awx-egress.yaml
  - sonarqube-egress.yaml
  - jenkins-egress.yaml
  - argocd-egress.yaml
  - obs-egress.yaml
  - wazuh-egress.yaml
  - shuffle-egress.yaml
  - hr-system-egress.yaml
  - object-admin-egress.yaml
  - demo-onprem-egress.yaml
  - ingress.yaml
