apiVersion: v1
kind: Service
metadata:
  name: pomerium
  namespace: pomerium
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
  labels:
    app.kubernetes.io/name: pomerium
    app.kubernetes.io/component: server
    app.kubernetes.io/part-of: platform-gitops
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: pomerium
    app.kubernetes.io/component: server
  ports:
    - name: http
      port: 80
      targetPort: http
      protocol: TCP
