apiVersion: v1
kind: ServiceAccount
metadata:
  name: pomerium
  namespace: pomerium
  annotations:
    argocd.argoproj.io/sync-wave: "-2"
  labels:
    app.kubernetes.io/name: pomerium
    app.kubernetes.io/part-of: platform-gitops
automountServiceAccountToken: false
