apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: soar-dash-01-pomerium-to-shuffle
  namespace: pomerium
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
  labels:
    app.kubernetes.io/name: pomerium
    app.kubernetes.io/component: server
    app.kubernetes.io/part-of: platform-gitops
spec:
  podSelector:
    matchLabels:
      app.kubernetes.io/name: pomerium
      app.kubernetes.io/component: server
  policyTypes:
    - Egress
  egress:
    - to:
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: shuffle
          podSelector:
            matchLabels:
              app.kubernetes.io/name: shuffle
              app.kubernetes.io/component: frontend
      ports:
        - port: 8080
          protocol: TCP
