---
netbird_domain: "netbird.imcherry5778.xyz"
netbird_acme_email: "admin@imcherry5778.xyz"
netbird_admin_email: "admin@imcherry5778.xyz"
cloudflare_api_token: "cfat_QY1fumjBjmKBp9UL0PNrdrtT4Y0qUQLgIBoHUx4m6e895359"

netbird_config_dir: "/etc/netbird"
netbird_data_dir: "/var/lib/netbird"
netbird_idp_data_dir: "/var/lib/netbird/idp"
netbird_letsencrypt_dir: "/var/lib/netbird/letsencrypt"

# Fixed container image digests
netbird_server_image: "netbirdio/netbird-server:v0.73.0@sha256:8d7fe3f415a35d8bef22e6bf036f66d2085aae43cdf5e6cf3a74a6ac6f0c7fa1"
netbird_dashboard_image: "netbirdio/dashboard:v2.90.8@sha256:6b3df5d07cbcf8fb81a6a18bb99fadb220e66a554c0e0fe71cd17a93c15769b1"
traefik_image: "traefik:v3.7.9@sha256:652929a140a32d7cafafb13c6cdfab5376cfeff800f51397b87b524501ed02a8"
