apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: aws-load-balancer-controller
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
    argocd.argoproj.io/sync-options: Prune=false
  labels:
    app.kubernetes.io/part-of: platform-gitops
spec:
  description: AWS-HR-01 private EKS internal ALB controller boundary
  sourceRepos: [https://aws.github.io/eks-charts]
  destinations:
    - {namespace: kube-system, name: hr-system-prod}
  clusterResourceWhitelist:
    - {group: networking.k8s.io, kind: IngressClass}
    - {group: elbv2.k8s.aws, kind: IngressClassParams}
    - {group: apiextensions.k8s.io, kind: CustomResourceDefinition}
    - {group: admissionregistration.k8s.io, kind: MutatingWebhookConfiguration}
    - {group: admissionregistration.k8s.io, kind: ValidatingWebhookConfiguration}
    - {group: rbac.authorization.k8s.io, kind: ClusterRole}
    - {group: rbac.authorization.k8s.io, kind: ClusterRoleBinding}
  namespaceResourceWhitelist:
    - {group: "", kind: Secret}
    - {group: "", kind: Service}
    - {group: "", kind: ServiceAccount}
    - {group: apps, kind: Deployment}
    - {group: rbac.authorization.k8s.io, kind: Role}
    - {group: rbac.authorization.k8s.io, kind: RoleBinding}
