apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: crowdsec
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  annotations:
    argocd.argoproj.io/sync-wave: "0"
  labels:
    app.kubernetes.io/part-of: platform-gitops
spec:
  project: crowdsec
  source:
    repoURL: ssh://git@ssh.github.com:443/ktcloud4-bean/platform.git
    targetRevision: main
    path: gitops/apps/crowdsec
    helm:
      releaseName: crowdsec
      valueFiles:
        - values-crowdsec-01.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: crowdsec-01
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - ApplyOutOfSyncOnly=true
      - ServerSideApply=true
      - PruneLast=true
      - PrunePropagationPolicy=foreground
