apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: demo-onprem
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  annotations:
    argocd.argoproj.io/sync-wave: "2"
  labels:
    app.kubernetes.io/part-of: platform-gitops
spec:
  project: demo-onprem
  source:
    repoURL: ssh://git@ssh.github.com:443/ktcloud4-bean/platform.git
    targetRevision: main
    path: gitops/apps/demo-onprem
  destination:
    server: https://kubernetes.default.svc
    namespace: demo-onprem
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - ApplyOutOfSyncOnly=true
      - PruneLast=true
      - PrunePropagationPolicy=foreground
