apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: hr-system
  namespace: argocd
  finalizers: [resources-finalizer.argocd.argoproj.io]
  annotations:
    argocd.argoproj.io/sync-wave: "3"
  labels:
    app.kubernetes.io/part-of: platform-gitops
spec:
  project: hr-system
  source:
    repoURL: ssh://git@ssh.github.com:443/ktcloud4-bean/platform.git
    targetRevision: d4e3455e8d8456208cdea7e0c8bd64dcbef8456b
    path: gitops/apps/hr-system
  destination:
    name: hr-system-prod
    namespace: hr-system
  syncPolicy:
    automated: {prune: true, selfHeal: true}
    syncOptions:
      - ApplyOutOfSyncOnly=true
      - PruneLast=true
      - PrunePropagationPolicy=foreground
