apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: hr-system
  namespace: argocd
  finalizers: [resources-finalizer.argocd.argoproj.io]
  annotations:
    argocd.argoproj.io/sync-wave: "3"
  labels:
    app.kubernetes.io/part-of: platform-gitops
spec:
  project: hr-system
  source:
    repoURL: ssh://git@ssh.github.com:443/ktcloud4-bean/platform.git
    targetRevision: 7915938df2b99419f911f60255fd8ce9a156e258
    path: gitops/apps/hr-system
  destination:
    name: hr-system-prod
    namespace: hr-system
  syncPolicy:
    automated: {prune: true, selfHeal: true}
    syncOptions:
      - ApplyOutOfSyncOnly=true
      - PruneLast=true
      - PrunePropagationPolicy=foreground
