apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: argocd
resources:
  - app-project.yaml
  - ingress-project.yaml
  - ingress-application.yaml
  - vault-project.yaml
  - vault-application.yaml
  - headlamp-project.yaml
  - headlamp-application.yaml
  - keycloak-project.yaml
  - keycloak-application.yaml
  - pomerium-project.yaml
  - pomerium-application.yaml
  - gitea-project.yaml
  - gitea-application.yaml
  - awx-project.yaml
  - awx-application.yaml
  - crowdsec-project.yaml
  - crowdsec-application.yaml
  - velero-project.yaml
  - velero-application.yaml
  - kyverno-project.yaml
  - kyverno-application.yaml
  - policy-baseline-project.yaml
  - policy-baseline-application.yaml
