apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: argocd
resources:
  - app-project.yaml
  - ingress-project.yaml
  - ingress-application.yaml
  - vault-project.yaml
  - vault-application.yaml
  - headlamp-project.yaml
  - headlamp-application.yaml
  - keycloak-project.yaml
  - keycloak-application.yaml
  - pomerium-project.yaml
  - pomerium-application.yaml
  - gitea-project.yaml
  - gitea-application.yaml
  - awx-project.yaml
  - awx-application.yaml
  - renovate-project.yaml
  - renovate-application.yaml
  - sonarqube-project.yaml
  - sonarqube-application.yaml
  - harbor-project.yaml
  - harbor-application.yaml
  - jenkins-project.yaml
  - jenkins-application.yaml
  - crowdsec-project.yaml
  - crowdsec-application.yaml
  - velero-project.yaml
  - velero-application.yaml
  - kyverno-project.yaml
  - kyverno-application.yaml
  - policy-baseline-project.yaml
  - policy-baseline-application.yaml
  - e2e-01-project.yaml
  - e2e-01-application.yaml
  - falco-project.yaml
  - falco-application.yaml
  - loki-project.yaml
  - loki-application.yaml
  - obs-project.yaml
  - obs-application.yaml
