apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kyverno-eks
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  annotations:
    argocd.argoproj.io/sync-wave: "0"
  labels:
    app.kubernetes.io/part-of: platform-gitops
spec:
  project: kyverno-eks
  source:
    repoURL: ssh://git@ssh.github.com:443/ktcloud4-bean/platform.git
    targetRevision: main
    path: gitops/apps/kyverno-eks
  destination:
    name: hr-system-prod
    namespace: kyverno
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - ApplyOutOfSyncOnly=true
      - ServerSideApply=true
      - PruneLast=true
      - PrunePropagationPolicy=foreground
