apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: pomerium
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  annotations:
    argocd.argoproj.io/sync-wave: "0"
  labels:
    app.kubernetes.io/part-of: platform-gitops
spec:
  project: pomerium
  source:
    repoURL: ssh://git@ssh.github.com:443/ktcloud4-bean/platform.git
    targetRevision: a433249bfcf96e385f51cea0b8ef02b5f16e23d3
    path: gitops/apps/pomerium
  destination:
    server: https://kubernetes.default.svc
    namespace: pomerium
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - ApplyOutOfSyncOnly=true
      - PruneLast=true
      - PrunePropagationPolicy=foreground
