apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: vault
  namespace: argocd
  labels:
    app.kubernetes.io/part-of: platform-gitops
spec:
  project: vault
  source:
    repoURL: ssh://git@ssh.github.com:443/ktcloud4-bean/platform.git
    targetRevision: main
    path: gitops/apps/vault
  destination:
    server: https://kubernetes.default.svc
    namespace: vault
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - ApplyOutOfSyncOnly=true
      - PruneLast=true
      - PrunePropagationPolicy=foreground
