apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - serviceaccount.yaml
  - trust-bundles.yaml
  - vault-agent-config.yaml
  - bootstrap-script.yaml
  - pvc.yaml
  - services.yaml
  - deployment.yaml
