apiVersion: v1
kind: ServiceAccount
metadata:
  name: gitea
  namespace: gitea
  annotations:
    argocd.argoproj.io/sync-wave: "-2"
  labels:
    app.kubernetes.io/name: gitea
    app.kubernetes.io/part-of: platform-gitops
automountServiceAccountToken: false
