FROM docker.io/library/debian@sha256:9bb8a3626890e084ab54e888fdd7c4b6d2f119071cd4c5dc5fecb4d73062aa5f

COPY proxmox-auto-install-assistant_9.2.7_amd64.deb /tmp/proxmox-auto-install-assistant.deb

RUN apt-get update \
    && DEBIAN_FRONTEND=noninteractive apt-get install -y --no-install-recommends \
       xorriso /tmp/proxmox-auto-install-assistant.deb \
    && test "$(dpkg-query -W -f='${Version}' proxmox-auto-install-assistant)" = "9.2.7" \
    && apt-get clean \
    && find /var/lib/apt/lists -mindepth 1 -delete \
    && unlink /tmp/proxmox-auto-install-assistant.deb

ENTRYPOINT ["/usr/bin/proxmox-auto-install-assistant"]
