apiVersion: v1
kind: ServiceAccount
metadata:
  name: keycloak
  namespace: keycloak
  annotations:
    argocd.argoproj.io/sync-wave: "-2"
  labels:
    app.kubernetes.io/name: keycloak
    app.kubernetes.io/part-of: platform-gitops
automountServiceAccountToken: false
