apiVersion: v1
kind: Service
metadata:
  name: keycloak
  namespace: keycloak
  annotations:
    argocd.argoproj.io/sync-wave: "-2"
  labels:
    app.kubernetes.io/name: keycloak
    app.kubernetes.io/component: server
    app.kubernetes.io/part-of: platform-gitops
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: keycloak
    app.kubernetes.io/component: server
  ports:
    - name: http
      port: 8080
      targetPort: http
      protocol: TCP
