apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - install.yaml
configMapGenerator:
  - name: loki-runtime-config
    namespace: loki
    files:
      - vault-agent.hcl=files/vault-agent.hcl
      - vault.crt=files/vault.crt
      - s3.crt=files/s3.crt
generatorOptions:
  disableNameSuffixHash: true
patches:
  - path: security-patch.yaml
