apiVersion: v1
kind: Service
metadata:
  name: traefik-metrics
  namespace: kube-system
  labels:
    app.kubernetes.io/name: traefik
    app.kubernetes.io/component: metrics
    app.kubernetes.io/part-of: platform-ingress
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/instance: traefik-kube-system
    app.kubernetes.io/name: traefik
  ports:
    - name: metrics
      protocol: TCP
      port: 9100
      targetPort: metrics
